### ISSUE TITLE
Version on Download

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/Athena#13]
On the ATHENA download screen, could you please put the version of the Vocabulary so the user knows before they download the whole thing?

**Comment by mpozhidaeva** [comment]
Thanks for your feedback! We have this issue in Athena tracker and we will inform you when it will be done.

**Comment by johnSamilin** [comment]
Hi @ericaVoss, sorry for the little delay,
you mean to put the CODE (CDM V5) value for each vocabulary in the modal window that's appearing after you click "Download Vocabularies" button?

**Comment by ericaVoss** [comment]
It would be good to know what you are downloading before downloading the entire thing.  But that can be implemented in any way you guys want.  Right now I have to wait for the entire thing to download before I even know what I downloaded.

**Comment by johnSamilin** [comment]
Let's clearify a little bit: 'The entire thing' is a bundle with the vocabularies that you selected on this page http://athena.ohdsi.org/vocabulary/list, right?

**Comment by ericaVoss** [comment]
Yes, and regardless what you select to download every OMOP Vocabulary has a version.

```{SQL}
SELECT VOCABULARY_VERSION
FROM VOCABULARY
WHERE VOCABULARY_ID = 'None'
```

Right now we are running `v5.0 01-DEC-17` in my shop. 

I'd like to know at the point of download what VOCABULARY_VERSION is being downloaded.  If I downloaded a copy last week and want to download one this week I have no way to know what version is currently released.  Unless it is listed somewhere that I'm not seeing.

**Comment by ericaVoss** [comment]
Hoping we can still add this in.  I just downloaded the newest Vocabulary, I'll have no idea what version until I download all the files, unzip, and open up the VOCABULARY.csv.

**Comment by acumarav** [comment]
Hello @ericaVoss ,
I am going to implement this change shortly, just please confirm that I got them right.

Q0. I assume you cares about 'vocabulary version' value of the available/downloaded vocabularies, is not it?

Q1. Do you need 'Latest Update' value which you can see in the grid currenlty?



**Action plan:**
1. So that user was able to see actual version of the available Vocaburies before the download we going to:
 add 'VOCABULARY VERSION'  column to the vocabularies grid which you user can see (http://athena.ohdsi.org/vocabulary/list)

2. So that user was able to see which versions have been packed into downloadable zip bundle we going to:
  add 'VOCABULARY VERSION' column to the DOWNLOAD HISTORY expaded grid which user can see (http://athena.ohdsi.org/vocabulary/download-history)
(this column will be filled in only for the newly created bundle)


@ericaVoss please confirm what you agree with the proposed Action Plan or voice your objections.

**Comment by acumarav** [comment]
PRs have been opened:
https://github.com/OHDSI/Athena/pull/68
https://github.com/OHDSI/AthenaUI/pull/36

**Comment by ericaVoss** [comment]
is it possible to see the Version ID of the Vocabulary yet?  I also need to see the version of individual Vocabularies, like MedDRA.  Need to know what version it is on.

**Comment by gowthamrao** [comment]
Thank you @ericaVoss

**Comment by olga-ganina** [comment]
@ericaVoss  it is implemented and available at http://athena.ohdsi.org

**Comment by ericaVoss** [comment]
Thank you!

![bitmoji](https://render.bitstrips.com/v2/cpanel/76e9e275-30ca-4440-ba0e-2fcf2e244b95-5f1fcccf-7d9e-4ad7-9aa6-6b4aed4dbd29-v1.png?transparent=1&palette=1&width=246)
