### ISSUE TITLE
Add return address and standard return text into license request notification.

### ISSUE THREAD

**Issue by cgreich** [OHDSI/Athena#58]
The notification is currently sent from Athena [pallas@ohdsi.org]. Instead, I need it to go to the requesting user. So, please add as the return_to address the name and email address of the requesting user, e.g. "Zhang hui (1440859284@qq.com)". I am receiving quite a few of these, and have to copy and paste the email address from the text. Would make life easier.

**Comment by cgreich** [comment]
And these emails go to "admin@odysseusinc.com; reich@ohdsi.org". I should not be there. The admin can be forwarded to me.

**Comment by acumarav** [comment]
@cgreich - I have double-checked current behavior and I think we need to clarify a few things:

1. If user has requested access licenses for the vocabulary – an email with the grant license/reject goes to the Athena admins. Email is sending from pallas SMTP account to the Athena admins (there are two of them – as written above).

We cannot change email ‘from’ as it set by the mail server, so I would implement only:
- Extend email with the requester organization, request time and so on.

User reich receives those emails because it has an admin role. If to remove the admin role then the user will lose access to licenses management UI as well.

There are 2 ways how to grant/reject license request– by clicking in the email link or from the Athena UI. I both cases emails to the requester are get dispatched. It’s bit unclear why you send emails manually – Let’s add admin who approved the license to BCC so that he sees that user notification was sent. How do you think will it solve the problem?

**Comment by acumarav** [comment]
Test Video: https://drive.google.com/open?id=1A267hL9AeqdoRl6iDUps3BQC0l4y_G6M

PR: https://github.com/OHDSI/Athena/pull/111
