### ISSUE TITLE
Concept search improvement

### ISSUE THREAD

**Issue by dimshitc** [OHDSI/Athena#60]
1.
"(search_string" should be equal to "search_string"
If the key-word is in brackets, i.e. starts with "(" or "[", I need to put the bracket in the search string.

search string ='(hmo';
output:
http://athena.ohdsi.org/search-terms/terms?domain=Payer&page=1&pageSize=15&query=%28hmo

search string ='hmo';
output:
http://athena.ohdsi.org/search-terms/terms?domain=Payer&page=1&pageSize=15&query=hmo

Looks like "[", "(" and perhaps some other symbols shouldn't be treated as a part of the word.

2.
Would be nice to allow exact match search.

search string = "aspirin";
output: concepts with lower (concept_synonym_name) ='aspirin'
currently Athena gives all the concepts containg search string and there's no way to find this "aspirin" only.

**Comment by dimshitc** [comment]
And here was another example from @aostropolets 
https://github.com/OHDSI/Athena/issues/47

**Comment by pavgra** [comment]
Summarizing all requirements from @dimshitc, @cgreich, @aostropolets (treat as TODO):

**1) Stemming and indexing (problems with brackets)**

*Examples:*

a) Expected: should return results when searching:
http://athena.ohdsi.org/search-terms/terms?vocabulary=NDC&page=1&pageSize=15&query=fiasp

Actual: returns results only with `[` in the search string:
http://athena.ohdsi.org/search-terms/terms?vocabulary=NDC&page=1&pageSize=15&query=%5Bfiasp

b) Expected: return same results (23 rows) as the following query:
```
SELECT c2.concept_id, c2.concept_name, c2.concept_class_id, c2.domain_id, c2.vocabulary_id
FROM concept c2
WHERE c2.vocabulary_id IN ('CPT4', 'SNOMED', 'HCPCS')
AND c2.standard_concept = 'S'
AND c2.domain_id = 'Procedure'
AND c2.domain_id = 'Procedure'
AND lower(c2.concept_name) LIKE '%vasectomy%';
```

Actual: returns 17 rows
http://athena.ohdsi.org/search-terms/terms?vocabulary=CPT4&vocabulary=SNOMED&vocabulary=HCPCS&standardConcept=Standard&domain=Procedure&page=1&pageSize=15&query=vasectomy

**2) Preference of perfect match over a keyword in string results**

*Examples:*

Expected: search string = "aspirin"; return most exact match first, just "Aspirin" should be number 1

Actual: currently Athena gives all the concepts containing the search string in mixed way


**3) Preference for all keywords found over some keywords found when >1 keywords are put in**

**4) Enable partial concept code search (e.g. when zeros are missing)**

Expected: same results as for
http://athena.ohdsi.org/search-terms/terms?vocabulary=NDC&page=1&pageSize=15&query=00169320111

Actual:
http://athena.ohdsi.org/search-terms/terms?vocabulary=NDC&page=1&pageSize=15&query=169320111

**Comment by aklochkova** [comment]
Question about p.1: did I understand correctly that we don't want to store brackets and parentheses in SOLR? What about braces?

**Comment by dimshitc** [comment]
If search string is "aaaa", it should find "[aaaa", "aaaa", "[aaaa}", etc.
If search string is "[aaaa" it should find "[aaaa", "[aaaa}" only.

Yes, Braces should have the same behaviour as brackets and parentheses.

**Comment by aklochkova** [comment]
One more PR is here: https://bitbucket.org/Odysseus/dockerenv/pull-requests/105/athena-60-added-mapping-solrtxt-to-solr/diff

**Comment by TinyRickC137** [comment]
>
> 5) Enable exact search
> If a search string is put into double quotes - search for the exact match (Google-alike)

What do you think of improving special symbols further?  
Like adding special symbols to tag something search result **must include** and **must exclude**?

**Comment by cgreich** [comment]
Again, if the priority of partially matched results is below that of fully matched results the "must include" is not needed. The "must exclude" I like though. In many search engines the minus sign is used for that. We could do that as well.

**Comment by dimshitc** [comment]
> In many search engines the minus sign is used for that
You need to think twice about this: we have all those LOINC codes, Drug names such as Co-amilofruse , and other Co-something.

**Comment by pavgra** [comment]
@aklochkova, @wivern, I see that the merged PR allows doing an exact search only for the whole search phrase, while Google allows wrapping only selected parts of a phrase into quotes and leaving other parts for fuzzy search. Please work on this. Tagging @olga-ganina for awareness

https://github.com/OHDSI/Athena/pull/66

**Comment by pbr6cornell** [comment]
A plea:  We need to coordinate vocabulary search between ATLAS and ATHENA.  In my opinion, it is quite harmful to the community that right now we have two different tools which produce different results when searching the same resource.  How can we make sure that lessons that have been learned from both sides are shared, and how can we avoid unnecessary redundant code?   Both should be running off a common set of WebAPI calls.

**Comment by gklebanov** [comment]
> Both should be running off a common set of WebAPI calls.

@pbr6cornell while I do completely support the idea that both ATHENA and WebAPI should be harmonized and produce the same results - both logic and visualization, but it does not mean that ATHENA should be built to utilize WebAPI for vocabulary search. In the MDM (Master Data Management) world, ATHENA is the system built to distribute the latest published vocabularies with consumer systems, with ATLAS/WebAPI being one of the receiving system. That said, we can discuss building a common reusable component that could / should be utilized by both ATHENA and ATLAS to deliver search capabilities in both systems. And I believe that you mean exactly that, correct?

**Comment by pbr6cornell** [comment]
To clarify, I am NOT saying that all ATHENA features need to run through WebAPI.   ATHENA's main purpose, and original sole intent, was to provide a distribution mechanism for the OHDSI standardized vocabularies, and I fully support whatever technologies the team is using to make sure that works well for the community.

I'm talking specifically about the user interface and backend technology to facilitate vocabulary search, which was a feature first introduced in ATLAS/WebAPI from the beginning, and was later added into ATHENA.  Through an unfortunate series of events that we don't need to revisit, these development activities were not coordinated, and as a result, we've ended up with 2 different UIs that use 2 different back-end technologies, but most worrisome from my perspective, provide the user 2 different search results when querying for the same exact input string against the same version of the vocabulary.   I very much want to see this problem go away, sooner rather than later.

As part of the ATLAS 2.8 development planning, one of the specific items expected to be released is an improved vocabulary search experience from a performance optimization perspective, which will likely involve using SOLR back-end but also involves cleaning up the SQL queries which return 'related concepts' and display 'hierarchy'.  @fdefalco is leading that effort, and I know he's already had prior discussions with @pavgra about the next steps for that.   This thread is talking about decisions of how to handle the user input when doing string search, to whatever extent possible, I want to make sure we don't end up in a situation where ATHENA is applying one set of rules and ATLAS is applying a different set of rules.  If the appropriate approach is to establish one shared component that both UIs can utilize, then I'm all for it.

**Comment by cgreich** [comment]
> I am NOT saying that all ATHENA features need to run through WebAPI. 

Whatever technology guys you are using - I agree the really important piece is identical behavior and same (or very similar) UI.

BTW: Is Ithaka going to be part of the overhaul?

> cleaning up the SQL queries which return 'related concepts' and display 'hierarchy

My plea to @fdefalco and @pavgra: Please talk to the vocab group. Please please don't second guess.

**Comment by gklebanov** [comment]
great - agree with both @pbr6cornell @cgreich on all counts

**Comment by olga-ganina** [comment]
Implemented and available at http://athena.ohdsi.org
