### ISSUE TITLE
Performance: concept load without hierarchy 

### ISSUE THREAD

**Issue by olga-ganina** [OHDSI/Athena#96]
Relates #82 

Load hierarchy diagram data on clicking on hierarchy button instead of loading it on concept page opening

**Comment by acumarav** [comment]
Currently, Athena UI retrieves the full graph during the rendering table view just in order to determine if it should show  **Hierarchy** tab header.

There are 2 options how to implement optimization - 
Plan A. implement a lightweight REST method to get only a boolean flag indicating that the concept has relations and a hierarchy graph can be rendered.

Plan B. render table view with disabled Hierarchy tab, make full graph request in the background and enable tab only if data for the graph has been received. 

I think that we should try A first as it reduces the overall load because graph info will be fetched  every time but only in the rear case when the user switches to the **Hierarchy** tab.

**Comment by acumarav** [comment]
PRs: 
https://github.com/OHDSI/AthenaUI/pull/59
https://github.com/OHDSI/Athena/pull/102

Test: 
https://drive.google.com/file/d/1aRc8TJ3J3e6LkfQ8YZDaox2IpD3VjA1_/view?usp=sharing
